# Generated by Django 5.1.3 on 2024-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrutiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrutinyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('scrutiny_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AudioRecord',
        ),
    ]
